# Generated by Django 4.1.5 on 2023-01-26 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_payments_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='isPaid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Payments',
        ),
    ]
