# Generated by Django 4.1.5 on 2023-01-26 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_order_ispaid_order_payment_status_delete_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_failure_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_success_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
